# src/Blogger/BlogBundle/Resources/config/routing.yml

BloggerBlogBundle_homepage:
    pattern:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        methods: GET
        
BloggerBlogBundle_about:
    pattern: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        methods: GET
        
BloggerBlogBundle_contact:
    pattern: /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        methods: GET|POST
        
BloggerBlogBundle_blog_show:
    pattern: /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        methods: GET
        id: \d+
        
BloggerBlogBundle_comment_create:
    pattern: /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        methods: POST
        blog_id: \d+